GET http://localhost:3500/api

### POST http://localhost:3500/api Content-Type: application/json

{
"title":"title", "source":"source", "gitRepo":"gitRepo", "description":"description", "imageSource":"imageSource"
}

### PATCH http://localhost:3500/api/6890a1e6ac9ba01e0db212d1 Content-Type: application/json

{
"title":null, "source":null, "gitRepo":null, "description":"A custum profile to display my expertise and design skills. The projects tab includes a small REST API using node.js.", "imageSource":null
}

### DELETE http://localhost:3500/api/68904967dd674dbf135ba7ab