GET http://localhost:3500/api

###
POST http://localhost:3500/api
Content-Type: application/json

{
    "title":"title",
    "source":"source",
    "gitRepo":"gitRepo",
    "description":"description",
    "imageSource":"imageSource"
}


###
PATCH http://localhost:3500/api/6890437899999bacd918d82f
Content-Type: application/json

{
    "title":"New Title",
    "source":null,
    "gitRepo":null,
    "description":null,
    "imageSource":null
}