###
POST http://localhost:3500/api
Content-Type: application/json

{
    "title": "Personal Profile",
        "imageSource":
            "https://www.dropbox.com/scl/fi/iur449qpn39edog3n4gx9/user.png?rlkey=fph21qkf6p6r6nnyispn52osb&st=f8jmdoex&raw=1",
        "source": "#",
        "gitRepo": "https://github.com/michyhems/Profile/tree/master",
        "description":
            "A custum profile to display my expertise and design skills."
}

###
POST http://localhost:3500/api
Content-Type: application/json

{
    "title": "Sorting Visualiser",
        "imageSource":
            "https://www.dropbox.com/scl/fi/lxwvspq2aowv9w9671ysv/sortingalg.png?rlkey=bj4zfbluao2mwbgucxmt84cha&st=5f8tnauc&raw=1",
        "source": "https://michyhems.github.io/SortingVisualiser/",
        "gitRepo": "https://github.com/michyhems/SortingVisualiser/tree/master",
        "description": "A sorting visualiser."
}

###
POST http://localhost:3500/api
Content-Type: application/json

{
    "title": "Sudoku",
        "imageSource":
            "https://www.dropbox.com/scl/fi/y3l037ssd5zhnsnutbw4h/sadokuIcon.png?rlkey=dgtqhl82ehojd0elw7cgr3eoi&st=uui4do9b&raw=1",
        "source": "https://michyhems.github.io/Sudoku/",
        "gitRepo": "https://github.com/michyhems/Sudoku/tree/master",
        "description":
            "I developed an interest in the brain teaser game, Sadoku. I wanted to see if I could build it and apply a novel idea for toggling dark mode."
}

###
POST http://localhost:3500/api
Content-Type: application/json

{
    "title": "3D Tooth Surgery",
        "imageSource":
            "https://www.dropbox.com/scl/fi/dt4uox8hs1zcl2icqjq3n/tooth.png?rlkey=w1coz641jpdcq3i6647ijni3l&st=vqtqbf9e&raw=1",
        "source": "https://www.youtube.com/watch?v=fgLgKa1RRfw",
        "gitRepo": "",
        "description":
            "While the skillset that this project showcases is not necessarily universal, it does represent my ability to learn new technologies and adapt to the given situation. As I said in the Experience section, Neither I nor any members of my team had any experience in animation or 3D modelling before undertaking this project",
}

###
POST http://localhost:3500/api
Content-Type: application/json

{
    "title": "Essay on Prototype-Oriented Programming",
        "imageSource":
            "https://www.dropbox.com/scl/fi/lqh0cjptgkwmt818jdyc8/research.png?rlkey=074cay2wgs3nzetmlpdy2295e&st=nh6zv1a7&raw=1",
        "source": "https://drive.google.com/file/d/1rs7A6NWjWMnoefbN3Kkhq25zPEHB2mQs/view?usp=sharing",
        "gitRepo": "",
        "description":
            "In my final year of University I was tasked with writing a ten page essay on a topic of my choice. The only restriction being that it could not be a 'regurgitation of the internet'. It had to be our own words and display our own understanding of the research we conducted. This essay shows my ability to communicate complex ideas clearly and effectively in the written form.",
}